# all directories should have a trailing forward slash /
error_directory = "./logs/"
data_directory = "./data/"


[tasks]

[tasks.task_1]
model_output_filename = "task_1.md"
model_output_directory = "./help/"
models = ["task_1"]

[tasks.task_1.model]
model_module_name = "model_front"
data_filter_conditions = ["filter_conditions_for_data_filename_for_task_1"]
