# all directories should have a trailing forward slash /
error_directory = "./logs/"
data_directory = "./data/"


[level_0]

[level_0.level_1]
model_output_filename = "changelog.md"
model_output_directory = "./help/"
models = ["changelog"]
markdown_header = """\
# Changelog

These are our release changelogs. We try to release an update every week on Warp Wednesday!

"""

[level_0.level_1.level_2]
model_module_name = "model_channel_versions"
data_filter_conditions = ["channel_versions"]
